'use strict';

// Creates a .env for a local demo with random secrets: database passwords, the
// operator login and one device key. The generated operator password is printed
// once and only its hash is stored.
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { hashPassword } = require('../src/auth');

const target = path.join(__dirname, '..', '.env');
if (fs.existsSync(target)) {
  console.error('.env already exists; delete it first if you want a new one.');
  process.exit(1);
}

const random = (bytes) => crypto.randomBytes(bytes).toString('hex');
const password = crypto.randomBytes(12).toString('base64url');

const lines = [
  '# Generated by `npm run init-env` for a local demo. Never commit this file.',
  '',
  '# Database (docker compose creates both users from these values)',
  'DB_HOST=127.0.0.1',
  'DB_PORT=3306',
  'DB_NAME=locatecabs',
  'DB_USER=locatecabs',
  `DB_PASS=${random(16)}`,
  `DB_ROOT_PASS=${random(16)}`,
  '',
  '# Operator login for the web UI',
  'APP_USER=operator',
  `APP_PASSWORD_HASH=${hashPassword(password)}`,
  '',
  '# One key per device: id:64 hex characters, comma separated',
  `DEVICE_KEYS=taxi1:${random(32)}`,
  '',
  '# Deploy webhook, disabled while the secret is empty',
  'GITHUB_WEBHOOK_SECRET=',
  'DEPLOY_DIR=',
  'DEPLOY_BRANCH=master',
  '',
];
fs.writeFileSync(target, lines.join('\n'), { mode: 0o600 });

console.log('Created .env');
console.log('Web login: operator');
console.log(`Password:  ${password}   (shown only now; only its hash is stored in .env)`);
